CREATE TABLE orders (
    order_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR2(100) NOT NULL,
    order_date    DATE DEFAULT SYSDATE,
    total_amount  NUMBER(10, 2) DEFAULT 0,
    delivery_date DATE,
    order_status  VARCHAR2(100) NOT NULL
);
