/********************************************/
-- AUTO RELEASE: qa-20250605
/********************************************/

----------------------------------------------
-- SECTION: MIGRATIONS (changes/)
----------------------------------------------
----------------------------------------------
-- SECTION: SCHEMA (FULL if first release)
----------------------------------------------
-- SCHEMA OBJECT: schema/functions/get_full_name.sql
CREATE OR REPLACE FUNCTION get_full_name(p_first_name VARCHAR2, p_last_name VARCHAR2)
RETURN VARCHAR2
IS
BEGIN
    RETURN INITCAP(p_first_name || ' ' || p_last_name);
END;



-- SCHEMA OBJECT: schema/tables/orders.sql
CREATE TABLE orders (
    order_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR2(100) NOT NULL,
    order_date    DATE DEFAULT SYSDATE,
    total_amount  NUMBER(10, 2) DEFAULT 0
);



